# Override the default values for the trustee chart
# This lists the secret resources that are uploaded to your chosen ESO backend (default: Vault).
# It does not contain the secrets themselves, only references to Vault paths.
kbs:
  secretResources:
    - name: "kbsres1"
      key: "secret/data/hub/kbsres1"
    - name: "passphrase"
      key: "secret/data/hub/passphrase"
    - name: "spire-cert"
      key: "secret/data/hub/spire-cert"
    - name: "spire-key"
      key: "secret/data/hub/spire-key"
