# Override the default values for the trustee chart
# This lists the secret resources that are uploaded to your chosen ESO backend (default: Vault).
# It does not contain the secrets themselves, only references to Vault paths.
#
# NOTE: When adding new CoCo workloads to coco.workloads, you must also add
# corresponding spire-cert-{workload} and spire-key-{workload} entries here
kbs:
  secretResources:
    - name: "kbsres1"
      key: "secret/data/hub/kbsres1"
    - name: "passphrase"
      key: "secret/data/hub/passphrase"
    # SPIRE x509pop certificates per workload type
    - name: "spire-cert-qtodo"
      key: "secret/data/hub/spire-cert-qtodo"
    - name: "spire-key-qtodo"
      key: "secret/data/hub/spire-key-qtodo"
  caCert: |
    -----BEGIN CERTIFICATE-----
    MIIFOzCCAyOgAwIBAgIUUoj5ov8plRtxd63WJyOiW5S7/3kwDQYJKoZIhvcNAQEL
    BQAwLTEPMA0GA1UEAwwGS0JTLUNBMRowGAYDVQQKDBFWYWxpZGF0ZWRQYXR0ZXJu
    czAeFw0yNTEyMDkxNzQxMjdaFw0yNjEyMDkxNzQxMjdaMC0xDzANBgNVBAMMBktC
    Uy1DQTEaMBgGA1UECgwRVmFsaWRhdGVkUGF0dGVybnMwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQDPV8m1OFcmoW7RNC+KDu8tW3GhaHIXSmyJ5gC9Nqa8
    RkL+AKDO58aOKJ6zzVNsBfkmsiXhD69fFaDDxcdpp++JlJ8q2Pajcp9OenVUsMsu
    WSdy0TlJMYVzrIaXfWmDKulZMeMtZR/4H4RWqIF4UqoKFW83pDZxdKUiaeS4X8qb
    lgfJDgoDhOhn9403q4xvAyDnrffkK8HA7wY0l6LS4FfIre5cjyzxrIpN2GQsl33Y
    GQGtpHTHWcmHJtYC76kcIaHlGiK6LonHtfBUq1QKNyKc/NiHPgxcDtFR8xc6mXmm
    nvVVEBYWLUstyLCiRzQr7TAIp0Wy4MedUmFCRdGOf8O22gmyHNmEYUbO5viWzSmp
    N36NGlsKEehrcXZJxh2a3SYsh+ubt3RPrc2DAHGhj4OdbKMI04z8pHh3yMoJ5ZPQ
    mU0RloiwUOEXv2IzoI2ZBdMsqFJpqBeMCfKJ/ijDawWC+tiQtMrYmqUPLhm0mG6N
    0vJ6huDBKT8+7i+RuWsMdk7qBHCYdfp1929laqTD6FsmIyeSDWJqJpDb+fa6f71/
    t+nhfBFPVjLAB/yEa8yemf5sJ8wbmVNUhCHWnDEh7NmWHRDpJLkYXU2yqUdTDqoK
    N147WGzUGdZFX2i9iodfV/uJhXAD/ub8ZkGi3fPCSPL68ph9H3Xe2Je4Ao6sX/uO
    fQIDAQABo1MwUTAdBgNVHQ4EFgQU56N2tIaGQXvbFXf39LZhUr0NPKYwHwYDVR0j
    BBgwFoAU56N2tIaGQXvbFXf39LZhUr0NPKYwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAgEAX/nkliDSNIqSX6NZSMyB9G9qZJTVSrPkE8FCYvAFYfZi
    VPd3D112RO43/XbTl3RcuURpL0eX9B09btk6odFwmUOX8YltbfTWUjzjKQX1jA1N
    Mf2FlEZAWnffX+dy36mWoTg19z2/QMae0rC1FJxQWg8H+2HCj6Q4zbV1uhoXczM+
    DyDPz8dKap/6EI3Z4ehm5+VFquMCfU9LwTFo9oCgvjn/2Tz8DD2y86VDrkPkEpu6
    n8lwoSTwfVEIcMHieEGr8jRsVJYJGc3wC0Gn5caGrRTdzxtfMr2RM0MNSa1Lpnav
    hvGUDYxFASKnuSXvuVrlkgMcuZljSGTdfabznm1hrAcHeJpyklOT2FdlHfbVjwUr
    cu3PVdIWyIbZGIfG/RNj4a/Rw9MBM2/vHOs2E0UQA2NgTIza8HHnk6gMAeD9jgQr
    xFd0QjkbNu633c2WCmjDKzOAifVprNG2e3toVDDsDGzohbr0Vrc6WsqW7dLZ8sI1
    y1eJ/8Hfvs3dni1JE8HbX9xaJvOKYFh+oiQMa/4RdkcG16WKh9Hrx6FpOvdmBdUs
    +rRs1UYs3mY4AxNH3knvvDZ5urPUxE+ZnJ/BEFyTFa6KmxL1SYUOn1Nsr27qFVSo
    zFV3QZrfL79scOvhunN1B1HdncxvBxUqiK39XdmUD/2Fqxt0UBCE70nuLexw+1E=
    -----END CERTIFICATE-----
